name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          NODE_ENV: 'production'
          HOST: 'localhost'
          PORT: 4000
          file_name: .env
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm jest
      - run: npm run build
      - run: pm2 restart shani-account
